client_location: fsdfsdf
client_name: sdfs
client_token: dfsdf
data_push_interval: fsd
database: etimetracklite1
password: essl
server_key: sdfs
server_url: dfsdf
sql_server: DESKTOP-7QD3O04
username: essl
