client_location: fsdfsdf
client_name: sdfs
client_token: dfsdf
data_push_interval: fsd
database: eTimetracklite12
password: ' essl'
server_key: ''
server_url: dfsdf
sql_server: EC2AMAZ-TQLES2C
username: essl
